services:
  web:
    image: icpac/fast-cgan-web
    container_name: cgan-web
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # command: gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000
    env_file:
      - ./.env
    ports:
      - ${HOST_NET_IP:-172.17.0.1}:${APP_HOST_PORT:-8000}:8000
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: cgan-redis
    volumes:
      - ./data/redis:/data
    ports:
      - ${HOST_NET_IP:-172.17.0.1}:${REDIS_CACHE_PORT:-6379}:6379
