services:
  web:
    image: icpac/fast-cgan-web
    container_name: cgan-web
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000
    env_file:
      - ./.env
    ports:
      - ${APP_HOST_IP:-172.17.0.1}:${APP_HOST_PORT:-8000}:8000
    volumes:
      - ${GAN_FORECASTS_DIR:-./data/cgan}:${APP_DATA_DIR:-/code/app/data}/cgan-forecast}
      - ${IFS_FORECASTS_DIR:-./data/cgan}:${APP_DATA_DIR:-/code/app/data}/open-ifs}
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: cgan-redis
    volumes:
      - ./data/redis:/data
    ports:
      - ${REDIS_CACHE_HOST:-172.17.0.1}:${REDIS_CACHE_PORT:-6379}:6379
