services:
  redis:
    image: redis:alpine
    container_name: ${REDIS_CNTR_NAME:-cgan-redis}
    volumes:
      - ${REDIS_DATA_DIR:-./data/redis}:/data
    ports:
      - ${REDIS_CACHE_HOST:-127.0.0.1}:${REDIS_CACHE_PORT:-6379}:6379

  api:
    image: ${API_IMAGE_NAME:-icpac/fast-cgan-api}
    container_name: ${API_CNTR_NAME:-cgan-api}
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn fastcgan.main:app --timeout ${GUNICORN_TIMEOUT:-300} --workers ${GUNICORN_WORKERS:-8} --worker-class uvicorn.workers.UvicornWorker --bind  0.0.0.0:8000
    environment:
      - REDIS_CACHE_HOST
      - REDIS_CACHE_PORT
      - REDIS_QUEUE_HOST
      - REDIS_QUEUE_PORT
      - REDIS_RATE_LIMIT_HOST
      - REDIS_RATE_LIMIT_PORT
      - USE_UI_FS=${USE_UI_FS:-True}
      - MASK_REGION=${MASK_REGION:-East Africa}
      - BASE_URL=${BASE_URL:-http://127.0.0.1:8000}
      - APP_VERSION=${APP_VERSION:-0.1}
      - SUB_PATH=${SUB_PATH:-}
      - FORECASTS_DATA_DIR=${APP_FORECASTS_DATA_DIR:-/opt/cgan/forecasts}
      - CACHE_DIR=${APP_CACHE_DIR:-/opt/app/cache}
      - LOGS_DIR=${APP_LOGS_DIR:-/opt/app/logs}
      - ENVIRONMENT=${ENVIRONMENT:-local}
    ports:
      - ${APP_HOST_IP:-127.0.0.1}:${APP_HOST_PORT:-8000}:8000
    volumes:
      - ${FORECASTS_DATA_DIR:-./data/forecasts}:${APP_FORECASTS_DATA_DIR:-/opt/cgan/forecasts}
      - ${LOGS_DIR:-./data/logs}:${APP_LOGS_DIR:-/opt/app/logs}
      - ${CACHE_DIR:-./data/cache}:${APP_CACHE_DIR:-/opt/app/cache}
    depends_on:
      - redis

  open-ifs: &light_data_jobs
    image: ${API_IMAGE_NAME:-icpac/fast-cgan-api}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${OPEN_IFS_JOBS_CNTR_NAME:-open-ifs-jobs}
    restart: ${RESTART_POLICY:-always}
    command: ${OPEN_IFS_JOBS_CMD:-python fastcgan/jobs/open_ifs.py}
    environment:
      - WORK_HOME=${WORK_HOME:-/opt/cgan}
      - JOBS_DATA_DIR=${APP_JOBS_DATA_DIR:-/opt/cgan/jobs}
      - FORECASTS_DATA_DIR=${APP_FORECASTS_DATA_DIR:-/opt/cgan/forecasts}
      - LOGS_DIR=${APP_LOGS_DIR:-/opt/cgan/logs}
    volumes:
      - ${FORECASTS_DATA_DIR:-./data/forecasts}:${APP_FORECASTS_DATA_DIR:-/opt/cgan/forecasts}
      - ${JOBS_DATA_DIR:-./data/jobs}:${APP_JOBS_DATA_DIR:-/opt/cgan/jobs}
      - ${LOGS_DIR:-./data/logs}:${APP_LOGS_DIR:-/opt/cgan/logs}
  
  files-cleaner:
    <<: *light_data_jobs
    image: ${API_IMAGE_NAME:-icpac/fast-cgan-api}
    container_name: ${FILES_CLEANER_JOBS_CNTR_NAME:-old-files-cleaner}
    command: ${FILES_CLEANER_JOBS_CMD:-python fastcgan/jobs/files_cleaner.py}
    environment:
      - WORK_HOME=${WORK_HOME:-/opt/cgan}
      - FORECASTS_DATA_DIR=${APP_FORECASTS_DATA_DIR:-/opt/cgan/forecasts}
      - MAX_FILE_AGE_DAYS=${MAX_FILE_AGE_DAYS:-1820}
    volumes:
      - ${FORECASTS_DATA_DIR:-./data/forecasts}:${APP_FORECASTS_DATA_DIR:-/opt/cgan/forecasts}

  jurre-brishti-ens: &cgan-forecast-model
    image: ${CGAN_IMAGE_NAME:-icpac/cgan-forecast-model}
    container_name: ${JURRE_ENS_JOBS_CNTR_NAME:-jurre-brishti-ens-jobs}
    build:
      context: .
      dockerfile: ${JOBS_DOCKERFILE:-jobs.Dockerfile}
      args:
        - JURRE_DIR=${JURRE_DIR:-Jurre_Brishti}
        - MVUA_DIR=${MVUA_DIR:-Mvua_Kubwa}
        - PYTHON_VERSION=3.10
    restart: ${RESTART_POLICY:-always}
    command: ${JURRE_ENS_JOBS_CMD:-python fastcgan/jobs/cgan_ifs.py -m 'jurre-brishti-ens'}
    environment:
      - WORK_HOME=${WORK_HOME:-/opt/cgan}
      - JOBS_DATA_DIR=${APP_JOBS_DATA_DIR:-/opt/cgan/jobs}
      - FORECASTS_DATA_DIR=${APP_FORECASTS_DATA_DIR:-/opt/cgan/forecasts}
      - LOGS_DIR=${APP_LOGS_DIR:-/opt/cgan/logs}
      - IFS_SERVER_HOST=${IFS_SERVER_HOST:-domain.example}
      - IFS_SERVER_USER=${IFS_SERVER_USER:-username}
      - IFS_PRIVATE_KEY=${IFS_PRIVATE_KEY:-/srv/ssl/private.key}
    volumes:
      - ${FORECASTS_DATA_DIR:-./data/forecasts}:${APP_FORECASTS_DATA_DIR:-/opt/cgan/forecasts}
      - ${JOBS_DATA_DIR:-./data/jobs}:${APP_JOBS_DATA_DIR:-/opt/cgan/jobs}
      - ${LOGS_DIR:-./data/logs}:${APP_LOGS_DIR:-/opt/cgan/logs}
      - ${MODELS_CONFIG_DIR:-./data/model}/jurre-brishti:${WORK_HOME:-/opt/cgan}/${JURRE_DIR:-Jurre_Brishti}/model-config
      - ${CGAN_LOCAL_CONFIG:-./configs/local_config.yaml}:${WORK_HOME:-/opt/cgan}/${JURRE_DIR:-Jurre_Brishti}/ensemble-cgan/dsrnngan/local_config.yaml:ro
      - ${JURRE_MAIN_CONFIG:-./configs/jurre-brishti/config.yaml}:${WORK_HOME:-/opt/cgan}/${JURRE_DIR:-Jurre_Brishti}/ensemble-cgan/dsrnngan/config.yaml:ro
      - ${JURRE_CGAN_DATA_PAPVT_NET_IPTHS_CONFIG:-./configs/jurre-brishti/data_paths.yaml}:${WORK_HOME:-/opt/cgan}/${JURRE_DIR:-Jurre_Brishti}/ensemble-cgan/dsrnngan/data_paths.yaml:ro
      - ${JURRE_CGAN_FORECAST_CONFIG:-./configs/jurre-brishti/forecast-ens.yaml}:${WORK_HOME:-/opt/cgan}/${JURRE_DIR:-Jurre_Brishti}/ensemble-cgan/dsrnngan/forecast.yaml:ro
      - ${IFS_SERVER_KEY:-./data/private/id_rsa.key}:${IFS_PRIVATE_KEY:-/srv/ssl/private.key}:ro

  jurre-brishti-counts:
    <<: *cgan-forecast-model
    image: ${CGAN_IMAGE_NAME:-icpac/cgan-forecast-model}
    container_name: ${JURRE_COUNTS_JOBS_CNTR_NAME:-jurre-brishti-counts-jobs}
    restart: ${RESTART_POLICY:-always}
    command: ${JURRE_COUNTS_JOBS_CMD:-python fastcgan/jobs/cgan_ifs.py -m 'jurre-brishti-count'}
    environment:
      - WORK_HOME=${WORK_HOME:-/opt/cgan}
      - JOBS_DATA_DIR=${APP_JOBS_DATA_DIR:-/opt/cgan/jobs}
      - FORECASTS_DATA_DIR=${APP_FORECASTS_DATA_DIR:-/opt/cgan/forecasts}
      - LOGS_DIR=${APP_LOGS_DIR:-/opt/cgan/logs}
      - IFS_SERVER_HOST=${IFS_SERVER_HOST:-domain.example}
      - IFS_SERVER_USER=${IFS_SERVER_USER:-username}
      - IFS_PRIVATE_KEY=${IFS_PRIVATE_KEY:-/srv/ssl/private.key}
    volumes:
      - ${FORECASTS_DATA_DIR:-./data/forecasts}:${APP_FORECASTS_DATA_DIR:-/opt/cgan/forecasts}
      - ${JOBS_DATA_DIR:-./data/jobs}:${APP_JOBS_DATA_DIR:-/opt/cgan/jobs}
      - ${LOGS_DIR:-./data/logs}:${APP_LOGS_DIR:-/opt/cgan/logs}
      - ${MODELS_CONFIG_DIR:-./data/model}/jurre-brishti:${WORK_HOME:-/opt/cgan}/${JURRE_DIR:-Jurre_Brishti}/model-config
      - ${CGAN_LOCAL_CONFIG:-./configs/local_config.yaml}:${WORK_HOME:-/opt/cgan}/${JURRE_DIR:-Jurre_Brishti}/ensemble-cgan/dsrnngan/local_config.yaml:ro
      - ${JURRE_MAIN_CONFIG:-./configs/jurre-brishti/config.yaml}:${WORK_HOME:-/opt/cgan}/${JURRE_DIR:-Jurre_Brishti}/ensemble-cgan/dsrnngan/config.yaml:ro
      - ${JURRE_CGAN_DATA_PAPVT_NET_IPTHS_CONFIG:-./configs/jurre-brishti/data_paths.yaml}:${WORK_HOME:-/opt/cgan}/${JURRE_DIR:-Jurre_Brishti}/ensemble-cgan/dsrnngan/data_paths.yaml:ro
      - ${JURRE_CGAN_FORECAST_CONFIG:-./configs/jurre-brishti/forecast-count.yaml}:${WORK_HOME:-/opt/cgan}/${JURRE_DIR:-Jurre_Brishti}/ensemble-cgan/dsrnngan/forecast.yaml:ro
      - ${IFS_SERVER_KEY:-./data/private/id_rsa.key}:${IFS_PRIVATE_KEY:-/srv/ssl/private.key}:ro

  mvua-kubwa-ens:
    <<: *cgan-forecast-model
    image: ${CGAN_IMAGE_NAME:-icpac/cgan-forecast-model}
    container_name: ${MVUA_ENS_JOBS_CNTR_NAME:-mvua-kubwa-ens-jobs}
    restart: ${RESTART_POLICY:-always}
    command: ${MVUA_ENS_JOBS_CMD:-python fastcgan/jobs/cgan_ifs.py -m 'mvua-kubwa-ens'}
    environment:
      - WORK_HOME=${WORK_HOME:-/opt/cgan}
      - JOBS_DATA_DIR=${APP_JOBS_DATA_DIR:-/opt/cgan/jobs}
      - FORECASTS_DATA_DIR=${APP_FORECASTS_DATA_DIR:-/opt/cgan/forecasts}
      - LOGS_DIR=${APP_LOGS_DIR:-/opt/cgan/logs}
      - IFS_SERVER_HOST=${IFS_SERVER_HOST:-domain.example}
      - IFS_SERVER_USER=${IFS_SERVER_USER:-username}
      - IFS_PRIVATE_KEY=${IFS_PRIVATE_KEY:-/srv/ssl/private.key}
    volumes:
      - ${FORECASTS_DATA_DIR:-./data/forecasts}:${APP_FORECASTS_DATA_DIR:-/opt/cgan/forecasts}
      - ${JOBS_DATA_DIR:-./data/jobs}:${APP_JOBS_DATA_DIR:-/opt/cgan/jobs}
      - ${LOGS_DIR:-./data/logs}:${APP_LOGS_DIR:-/opt/cgan/logs}
      - ${MODELS_CONFIG_DIR:-./data/model}/mvua-kubwa:${WORK_HOME:-/opt/cgan}/model
      - ${CGAN_LOCAL_CONFIG:-./configs/local_config.yaml}:${WORK_HOME:-/opt/cgan}/ensemble-cgan/dsrnngan/local_config.yaml:ro
      - ${MVUA_MAIN_CONFIG:-./configs/mvua-kubwa/config.yaml}:${WORK_HOME:-/opt/cgan}/ensemble-cgan/dsrnngan/config.yaml:ro
      - ${MVUA_CGAN_DATA_PATHS_CONFIG:-./configs/mvua-kubwa/data_paths.yaml}:${WORK_HOME:-/opt/cgan}/ensemble-cgan/dsrnngan/data_paths.yaml:ro
      - ${MVUA_CGAN_FORECAST_CONFIG:-./configs/mvua-kubwa/forecast-ens.yaml}:${WORK_HOME:-/opt/cgan}/ensemble-cgan/dsrnngan/forecast.yaml:ro
      - ${IFS_SERVER_KEY:-./data/private/id_rsa.key}:${IFS_PRIVATE_KEY:-/srv/ssl/private.key}:ro

  mvua-kubwa-counts:
    <<: *cgan-forecast-model
    image: ${CGAN_IMAGE_NAME:-icpac/cgan-forecast-model}
    container_name: ${MVUA_COUNTS_JOBS_CNTR_NAME:-mvua-kubwa-counts-jobs}
    restart: ${RESTART_POLICY:-always}
    command: ${MVUA_COUNTS_JOBS_CMD:-python fastcgan/jobs/cgan_ifs.py -m 'mvua-kubwa-ens'}
    environment:
      - WORK_HOME=${WORK_HOME:-/opt/cgan}
      - JOBS_DATA_DIR=${APP_JOBS_DATA_DIR:-/opt/cgan/jobs}
      - FORECASTS_DATA_DIR=${APP_FORECASTS_DATA_DIR:-/opt/cgan/forecasts}
      - LOGS_DIR=${APP_LOGS_DIR:-/opt/cgan/logs}
      - IFS_SERVER_HOST=${IFS_SERVER_HOST:-domain.example}
      - IFS_SERVER_USER=${IFS_SERVER_USER:-username}
      - IFS_PRIVATE_KEY=${IFS_PRIVATE_KEY:-/srv/ssl/private.key}
    volumes:
      - ${FORECASTS_DATA_DIR:-./data/forecasts}:${APP_FORECASTS_DATA_DIR:-/opt/cgan/forecasts}
      - ${JOBS_DATA_DIR:-./data/jobs}:${APP_JOBS_DATA_DIR:-/opt/cgan/jobs}
      - ${LOGS_DIR:-./data/logs}:${APP_LOGS_DIR:-/opt/cgan/logs}
      - ${MODELS_CONFIG_DIR:-./data/model}/mvua-kubwa:${WORK_HOME:-/opt/cgan}/${MVUA_DIR:-Mvua_Kubwa}/model-config
      - ${CGAN_LOCAL_CONFIG:-./configs/local_config.yaml}:${WORK_HOME:-/opt/cgan}/${MVUA_DIR:-Mvua_Kubwa}/ensemble-cgan/dsrnngan/local_config.yaml:ro
      - ${MVUA_MAIN_CONFIG:-./configs/mvua-kubwa/config.yaml}:${WORK_HOME:-/opt/cgan}/${MVUA_DIR:-Mvua_Kubwa}/ensemble-cgan/dsrnngan/config.yaml:ro
      - ${MVUA_CGAN_DATA_PATHS_CONFIG:-./configs/mvua-kubwa/data_paths.yaml}:${WORK_HOME:-/opt/cgan}/${MVUA_DIR:-Mvua_Kubwa}/ensemble-cgan/dsrnngan/data_paths.yaml:ro
      - ${MVUA_CGAN_FORECAST_CONFIG:-./configs/mvua-kubwa/forecast-count.yaml}:${WORK_HOME:-/opt/cgan}/${MVUA_DIR:-Mvua_Kubwa}/ensemble-cgan/dsrnngan/forecast.yaml:ro
      - ${IFS_SERVER_KEY:-./data/private/id_rsa.key}:${IFS_PRIVATE_KEY:-/srv/ssl/private.key}:ro
